### ISSUE TITLE
On shutdown error

### ISSUE THREAD

**Issue by Exatoon27** [TonimatasMCDEV/PerWorldCommands#2]
### Problem
When I turn off the server this error appears, it only appears the second time I turn off the server, since if it is the first time I turn it off it does not occur.

### Error message

> [22:04:37 ERROR]: Error occurred while disabling PerWorldCommands v1.0.3 (Is it up to date?)
> java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.file.FileConfiguration.save(java.io.File)" because "net.tonimatasmc.perworldcommands.manager.ConfigManager.messages" is null
> 	at net.tonimatasmc.perworldcommands.manager.ConfigManager.saveMessages(ConfigManager.java:39) ~[PerWorldCommands+1.0.3.jar:?]
> 	at net.tonimatasmc.perworldcommands.manager.UnregisterManager.unregister(UnregisterManager.java:8) ~[PerWorldCommands+1.0.3.jar:?]
> 	at net.tonimatasmc.perworldcommands.PerWorldCommands.onDisable(PerWorldCommands.java:19) ~[PerWorldCommands+1.0.3.jar:?]
> 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.17.1.jar:git-Purpur-1428]
> 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[patched_1.17.1.jar:git-Purpur-1428]
> 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[patched_1.17.1.jar:git-Purpur-1428]
> 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:514) ~[patched_1.17.1.jar:git-Purpur-1428]
> 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.disablePlugins(CraftServer.java:495) ~[patched_1.17.1.jar:git-Purpur-1428]
> 	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1064) ~[patched_1.17.1.jar:git-Purpur-1428]
> 	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:855) ~[patched_1.17.1.jar:git-Purpur-1428]
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1356) ~[patched_1.17.1.jar:git-Purpur-1428]
> 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
> 	at java.lang.Thread.run(Thread.java:831) ~[?:?]

### Server Specifications

- Version: 1.17.1
- Server Software: PaperMC
- Java Version: 16

**Comment by TonimatasDEV** [comment]
> ### Problem
> When I turn off the server this error appears, it only appears the second time I turn off the server, since if it is the first time I turn it off it does not occur.
> 
> ### Error message
> > [22:04:37 ERROR]: Error occurred while disabling PerWorldCommands v1.0.3 (Is it up to date?)
> > java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.file.FileConfiguration.save(java.io.File)" because "net.tonimatasmc.perworldcommands.manager.ConfigManager.messages" is null
> > at net.tonimatasmc.perworldcommands.manager.ConfigManager.saveMessages(ConfigManager.java:39) ~[PerWorldCommands+1.0.3.jar:?]
> > at net.tonimatasmc.perworldcommands.manager.UnregisterManager.unregister(UnregisterManager.java:8) ~[PerWorldCommands+1.0.3.jar:?]
> > at net.tonimatasmc.perworldcommands.PerWorldCommands.onDisable(PerWorldCommands.java:19) ~[PerWorldCommands+1.0.3.jar:?]
> > at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.17.1.jar:git-Purpur-1428]
> > at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[patched_1.17.1.jar:git-Purpur-1428]
> > at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[patched_1.17.1.jar:git-Purpur-1428]
> > at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:514) ~[patched_1.17.1.jar:git-Purpur-1428]
> > at org.bukkit.craftbukkit.v1_17_R1.CraftServer.disablePlugins(CraftServer.java:495) ~[patched_1.17.1.jar:git-Purpur-1428]
> > at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1064) ~[patched_1.17.1.jar:git-Purpur-1428]
> > at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:855) ~[patched_1.17.1.jar:git-Purpur-1428]
> > at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1356) ~[patched_1.17.1.jar:git-Purpur-1428]
> > at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
> > at java.lang.Thread.run(Thread.java:831) ~[?:?]
> 
> ### Server Specifications
> * Version: 1.17.1
> * Server Software: PaperMC
> * Java Version: 16

Test the new version: [https://www.spigotmc.org/resources/perworldcommands-command-for-a-world-1-7-1-19.97003/updates](https://www.spigotmc.org/resources/perworldcommands-command-for-a-world-1-7-1-19.97003/updates)
