### ISSUE TITLE
[Features] World Tab completion

### ISSUE THREAD

**Issue by Lennord** [TonimatasMCDEV/PerWorldCommands#3]
Hello, 

Is it possible that when you block an commands, the completion tab is removed, that would be a good idea I think.

Example:

Delete /test1 in world "world_nether" -> Delete tab completion for the command /test1 in world "world_nether" without deleting the tab completions of other worlds where the command in question has not been blocked.

Have a good day !

**Comment by TonimatasDEV** [comment]
> Hello,
> 
> Is it possible that when you block an commands, the completion tab is removed, that would be a good idea I think.
> 
> Example:
> 
> Delete /test1 in world "world_nether" -> Delete tab completion for the command /test1 in world "world_nether" without deleting the tab completions of other worlds where the command in question has not been blocked.
> 
> Have a good day !

The only way to remove the tab key would be to lock the tab key in the whole server, you can't lock it in specific worlds, there are no variables to do that. Even if you could I would add it in the plugin.
